#!/usr/bin/env bash

if uname | grep -qiE "mingw|msys"; then
  EXE_SUFFIX=".exe"
else
  EXE_SUFFIX=""
fi

# Bootstap nim to make nimble work
if [ ! -f ~/.cache/nim-workspace/bin/nim$EXE_SUFFIX ]; then
  if uname | grep -qiE "mingw|msys"; then
    curl https://github.com/dom96/choosenim/releases/download/v0.8.4/choosenim-0.8.4_windows_amd64.exe \
      --output /tmp/choosenim.exe
    /tmp/choosenim.exe "#version-1-6" --nimbleDir:~/.cache/nim-workspace
  else
    curl https://raw.githubusercontent.com/yyoncho/choosenim/nimble-dir/scripts/choosenim-unix-init.sh -sSf | NIMBLE_BIN=~/.cache/nim-workspace sh -x
    chmod a+x ~/.cache/nim-workspace/choosenim
    ~/.cache/nim-workspace/choosenim "#version-1-6" --nimbleDir:~/.cache/nim-workspace
  fi
fi
